<?php

namespace AppBundle\Entity\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
        public function findAllOrdered()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i FROM AppBundle:Information i ORDER BY i.createdAt DESC'
            )
            ->getResult();
    }
}
