<?php

namespace AppBundle\Entity\Repository;

/**
 * PresenceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresenceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
