<?php

namespace AppBundle\Entity\Repository;

/**
 * ReplecementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplecementRepository extends \Doctrine\ORM\EntityRepository
{
}
