<?php

namespace AppBundle\Entity\Repository;

/**
 * StudentCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
